ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_MANUAL_AWAITING_TIME';
ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_CYCLE_AWAITING_WORK_DAYS';
ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_CYCLE_AWAITING_OFF_DAYS';
ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_CYCLE_AWAITING_START_DATE';
ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_CYCLE_AWAITING_TIME';
ALTER TYPE "SessionStep" ADD VALUE IF NOT EXISTS 'SHIFT_CYCLE_AWAITING_END_DATE';
