ALTER TABLE "shifts" ADD COLUMN "name" TEXT;

ALTER TYPE "SessionStep" ADD VALUE 'SHIFT_MANUAL_AWAITING_NAME';
ALTER TYPE "SessionStep" ADD VALUE 'SHIFT_CYCLE_AWAITING_NAME';
ALTER TYPE "SessionStep" ADD VALUE 'SHIFT_EDIT_AWAITING_NAME';
